version: '3'

services:

  mysql:
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: restaurant
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/migrations:/scripts:ro
    ports:
      - "3400:3306"

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8080:8080
    depends_on:
      - mysql
